In [ ]:
import pandas as pd
import numpy as np
import requests
import warnings
import matplotlib.pyplot as plt
import seaborn as sns
from bs4 import BeautifulSoup

warnings.filterwarnings("ignore")

In [ ]:
# URL
url = f'https://www.cbssports.com/nba/standings' #

# Send requests
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3'}

# Response
response = requests.get(url = url, headers = headers)

# Create a bs4 object to parse the HTML content
soup = BeautifulSoup(response.content, 'html.parser')

In [ ]:
# Find the tbody containing Eastern Conference Teams, you can use select('tbody')[0], means first tbody found

tbody = soup.select('tbody')[0]

In [ ]:
# Find all team names
team = []

for i in tbody.find_all('a'):
    text = i.get_text().strip()
    if text:
        team.append(text)

In [ ]:
# Data for Eastern Conference Teams

data = []
for row in tbody.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

In [ ]:
# Construct Data Frame for Eastern Conference Teams

team_df = pd.DataFrame(team, columns = ['Team'])
team_df

            Team
0      Cleveland
1         Boston
2       New York
3      Milwaukee
4        Indiana
5        Detroit
6        Atlanta
7        Orlando
8          Miami
9        Chicago
10      Brooklyn
11  Philadelphia
12       Toronto
13     Charlotte
14    Washington

In [ ]:
# Construct Data Frame for Eastern Conference Teams

team_data = pd.DataFrame(data).iloc[:, 2:]
team_data

,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,54,10,.844,—,122.9,111.5,11.4,29-4,25-6,11-1,37-7,W14,10-0,62.9,100.0%,100.0%
1,47,18,.723,7.5,116.9,108.2,8.7,23-11,24-7,11-2,32-11,W5,8-2,59.7,98.5%,100.0%
2,40,23,.635,13.5,116.9,112.8,4.1,21-11,19-12,10-3,28-13,L3,5-5,52.2,1.5%,100.0%
3,36,27,.571,17.5,114.6,112.5,2.1,21-11,14-16,6-6,26-18,L2,7-3,43.9,0.0%,88.5%
4,35,28,.556,18.5,116.4,115.4,1.0,19-9,15-18,7-5,20-20,L3,5-5,46.0,0.0%,98.0%
5,36,29,.554,18.5,114.7,113.1,1.6,17-14,19-15,4-9,24-20,W1,7-3,42.8,0.0%,88.6%
6,31,34,.477,23.5,117.3,119.7,-2.4,16-16,15-17,7-4,23-18,W3,5-5,39.0,45.7%,73.4%
7,30,36,.455,25.0,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,29,35,.453,25.0,110.0,110.5,-0.5,15-15,13-20,7-5,18-22,L4,3-7,38.5,29.8%,60.6%
9,27,38,.415,27.5,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,22,42,.344,32.0,105.2,111.6,-6.4,10-21,12-21,3-8,12-27,W1,2-8,31.0,0.0%,2.4%
11,22,42,.344,32.0,109.5,114.4,-4.9,12-21,10-21,3-10,14-26,L1,2-8,33.9,0.0%,23.6%
12,22,43,.338,32.5,110.7,115.8,-5.1,15-20,7-23,4-8,14-29,W1,5-5,28.2,0.0%,<1.0%
13,16,48,.250,38.0,105.3,112.8,-7.5,10-24,6-24,1-11,9-32,W2,2-8,24.1,0.0%,<1.0%
14,13,50,.206,40.5,108.4,120.5,-12.1,7-25,6-24,6-6,10-27,L1,4-6,15.6,0.0%,0.0%

In [ ]:
# Combine both Data Frame (Eastern Conference)

df_final = pd.concat([team_df, team_data], axis = 1)
df_final

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,54,10,.844,—,122.9,111.5,11.4,29-4,25-6,11-1,37-7,W14,10-0,62.9,100.0%,100.0%
1,Boston,47,18,.723,7.5,116.9,108.2,8.7,23-11,24-7,11-2,32-11,W5,8-2,59.7,98.5%,100.0%
2,New York,40,23,.635,13.5,116.9,112.8,4.1,21-11,19-12,10-3,28-13,L3,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,27,.571,17.5,114.6,112.5,2.1,21-11,14-16,6-6,26-18,L2,7-3,43.9,0.0%,88.5%
4,Indiana,35,28,.556,18.5,116.4,115.4,1.0,19-9,15-18,7-5,20-20,L3,5-5,46.0,0.0%,98.0%
5,Detroit,36,29,.554,18.5,114.7,113.1,1.6,17-14,19-15,4-9,24-20,W1,7-3,42.8,0.0%,88.6%
6,Atlanta,31,34,.477,23.5,117.3,119.7,-2.4,16-16,15-17,7-4,23-18,W3,5-5,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.0,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,35,.453,25.0,110.0,110.5,-0.5,15-15,13-20,7-5,18-22,L4,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,27.5,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Brooklyn,22,42,.344,32.0,105.2,111.6,-6.4,10-21,12-21,3-8,12-27,W1,2-8,31.0,0.0%,2.4%
11,Philadelphia,22,42,.344,32.0,109.5,114.4,-4.9,12-21,10-21,3-10,14-26,L1,2-8,33.9,0.0%,23.6%
12,Toronto,22,43,.338,32.5,110.7,115.8,-5.1,15-20,7-23,4-8,14-29,W1,5-5,28.2,0.0%,<1.0%
13,Charlotte,16,48,.250,38.0,105.3,112.8,-7.5,10-24,6-24,1-11,9-32,W2,2-8,24.1,0.0%,<1.0%
14,Washington,13,50,.206,40.5,108.4,120.5,-12.1,7-25,6-24,6-6,10-27,L1,4-6,15.6,0.0%,0.0%

In [ ]:
# Find the table containing (Western Conference Teams), you can use select('tbody')[1], means second tbody found

tbody1 = soup.select('tbody')[1]

In [ ]:
# Find all team names
team = []

for i in tbody1.find_all('a'):
    text = i.get_text().strip()
    if text:
        team.append(text)

In [ ]:
# Data for Western Conference Teams

data = []
for row in tbody1.find_all('tr'):
    col = row.find_all('td')
    col = [ele.text.strip() for ele in col]
    data.append([ele for ele in col if ele])
data = pd.DataFrame(data, columns = ['No.', 'Team', 'W', 'L', 'PCT', 'GB', 'PPG', 'OPPG', 'DIFF', 'HOME', 'ROAD', 'DIV', 'CONF', 'STRK', 'L10', 'W', 'DIV', 'POST'])

In [ ]:
# Construct Data Frame for Western Conference Teams

team_df2 = pd.DataFrame(team, columns = ['Team'])
team_df2

             Team
0   Oklahoma City
1          Denver
2     L.A. Lakers
3         Memphis
4         Houston
5      Golden St.
6       Minnesota
7   L.A. Clippers
8      Sacramento
9          Dallas
10        Phoenix
11       Portland
12    San Antonio
13    New Orleans
14           Utah

In [ ]:
# Construct Data Frame for Western Conference Teams

team_data2 = pd.DataFrame(data).iloc[:, 2:]
team_data2

,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,53,12,.815,—,119.7,107.1,12.6,28-5,24-7,11-4,32-11,L1,8-2,66.1,100.0%,100.0%
1,42,23,.646,11.0,121.5,116.6,4.9,22-9,20-14,7-5,25-14,W1,6-4,52.8,0.0%,100.0%
2,40,23,.635,12.0,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
3,41,24,.631,12.0,122.6,116.8,5.8,23-10,18-14,10-5,24-16,W3,5-5,52.0,78.1%,99.8%
4,40,25,.615,13.0,112.9,108.9,4.0,22-10,18-14,12-3,24-16,W3,6-4,48.7,21.5%,94.4%
5,36,28,.563,16.5,113.3,111.2,2.1,18-13,18-15,2-10,20-19,W4,9-1,44.6,11.8%,65.0%
6,37,29,.561,16.5,112.8,109.2,3.6,18-14,19-15,7-5,26-18,W5,6-4,45.8,0.0%,78.9%
7,35,29,.547,17.5,110.8,108.7,2.1,22-10,13-19,7-7,21-21,W3,4-6,46.8,47.9%,85.7%
8,33,30,.524,19.0,116.8,114.9,1.9,16-14,17-16,4-8,23-21,L1,6-4,41.7,1.7%,31.5%
9,33,33,.500,20.5,114.8,114.5,0.3,19-15,14-18,8-5,23-23,W1,3-7,43.8,0.0%,61.3%
10,30,35,.462,23.0,114.5,116.5,-2.0,18-13,12-22,8-4,20-23,L1,4-6,37.7,0.0%,3.5%
11,28,37,.431,25.0,110.5,114.4,-3.9,16-15,12-22,5-9,15-29,L3,5-5,32.4,0.0%,0.0%
12,26,37,.413,26.0,113.7,116.1,-2.4,15-15,10-21,3-11,18-25,L3,2-8,35.9,0.0%,<1.0%
13,17,48,.262,36.0,110.8,119.1,-8.3,11-21,6-27,3-12,11-32,L4,4-6,24.7,0.0%,0.0%
14,15,50,.231,38.0,112.5,119.8,-7.3,8-24,7-26,2-9,7-36,L6,2-8,24.3,0.0%,0.0%

In [ ]:
# Combine both Data Frame (Western Conference)

df_final2 = pd.concat([team_df2, team_data2], axis = 1)
df_final2

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Oklahoma City,53,12,.815,—,119.7,107.1,12.6,28-5,24-7,11-4,32-11,L1,8-2,66.1,100.0%,100.0%
1,Denver,42,23,.646,11.0,121.5,116.6,4.9,22-9,20-14,7-5,25-14,W1,6-4,52.8,0.0%,100.0%
2,L.A. Lakers,40,23,.635,12.0,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
3,Memphis,41,24,.631,12.0,122.6,116.8,5.8,23-10,18-14,10-5,24-16,W3,5-5,52.0,78.1%,99.8%
4,Houston,40,25,.615,13.0,112.9,108.9,4.0,22-10,18-14,12-3,24-16,W3,6-4,48.7,21.5%,94.4%
5,Golden St.,36,28,.563,16.5,113.3,111.2,2.1,18-13,18-15,2-10,20-19,W4,9-1,44.6,11.8%,65.0%
6,Minnesota,37,29,.561,16.5,112.8,109.2,3.6,18-14,19-15,7-5,26-18,W5,6-4,45.8,0.0%,78.9%
7,L.A. Clippers,35,29,.547,17.5,110.8,108.7,2.1,22-10,13-19,7-7,21-21,W3,4-6,46.8,47.9%,85.7%
8,Sacramento,33,30,.524,19.0,116.8,114.9,1.9,16-14,17-16,4-8,23-21,L1,6-4,41.7,1.7%,31.5%
9,Dallas,33,33,.500,20.5,114.8,114.5,0.3,19-15,14-18,8-5,23-23,W1,3-7,43.8,0.0%,61.3%
10,Phoenix,30,35,.462,23.0,114.5,116.5,-2.0,18-13,12-22,8-4,20-23,L1,4-6,37.7,0.0%,3.5%
11,Portland,28,37,.431,25.0,110.5,114.4,-3.9,16-15,12-22,5-9,15-29,L3,5-5,32.4,0.0%,0.0%
12,San Antonio,26,37,.413,26.0,113.7,116.1,-2.4,15-15,10-21,3-11,18-25,L3,2-8,35.9,0.0%,<1.0%
13,New Orleans,17,48,.262,36.0,110.8,119.1,-8.3,11-21,6-27,3-12,11-32,L4,4-6,24.7,0.0%,0.0%
14,Utah,15,50,.231,38.0,112.5,119.8,-7.3,8-24,7-26,2-9,7-36,L6,2-8,24.3,0.0%,0.0%

In [ ]:
# Combine Eastern and Western Conference Data via pd.concat

df_combined = pd.concat([df_final, df_final2], axis = 0)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,54,10,.844,—,122.9,111.5,11.4,29-4,25-6,11-1,37-7,W14,10-0,62.9,100.0%,100.0%
1,Boston,47,18,.723,7.5,116.9,108.2,8.7,23-11,24-7,11-2,32-11,W5,8-2,59.7,98.5%,100.0%
2,New York,40,23,.635,13.5,116.9,112.8,4.1,21-11,19-12,10-3,28-13,L3,5-5,52.2,1.5%,100.0%
3,Milwaukee,36,27,.571,17.5,114.6,112.5,2.1,21-11,14-16,6-6,26-18,L2,7-3,43.9,0.0%,88.5%
4,Indiana,35,28,.556,18.5,116.4,115.4,1.0,19-9,15-18,7-5,20-20,L3,5-5,46.0,0.0%,98.0%
5,Detroit,36,29,.554,18.5,114.7,113.1,1.6,17-14,19-15,4-9,24-20,W1,7-3,42.8,0.0%,88.6%
6,Atlanta,31,34,.477,23.5,117.3,119.7,-2.4,16-16,15-17,7-4,23-18,W3,5-5,39.0,45.7%,73.4%
7,Orlando,30,36,.455,25.0,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,35,.453,25.0,110.0,110.5,-0.5,15-15,13-20,7-5,18-22,L4,3-7,38.5,29.8%,60.6%
9,Chicago,27,38,.415,27.5,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
10,Brooklyn,22,42,.344,32.0,105.2,111.6,-6.4,10-21,12-21,3-8,12-27,W1,2-8,31.0,0.0%,2.4%
11,Philadelphia,22,42,.344,32.0,109.5,114.4,-4.9,12-21,10-21,3-10,14-26,L1,2-8,33.9,0.0%,23.6%
12,Toronto,22,43,.338,32.5,110.7,115.8,-5.1,15-20,7-23,4-8,14-29,W1,5-5,28.2,0.0%,<1.0%
13,Charlotte,16,48,.250,38.0,105.3,112.8,-7.5,10-24,6-24,1-11,9-32,W2,2-8,24.1,0.0%,<1.0%
14,Washington,13,50,.206,40.5,108.4,120.5,-12.1,7-25,6-24,6-6,10-27,L1,4-6,15.6,0.0%,0.0%
0,Oklahoma City,53,12,.815,—,119.7,107.1,12.6,28-5,24-7,11-4,32-11,L1,8-2,66.1,100.0%,100.0%
1,Denver,42,23,.646,11.0,121.5,116.6,4.9,22-9,20-14,7-5,25-14,W1,6-4,52.8,0.0%,100.0%
2,L.A. Lakers,40,23,.635,12.0,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
3,Memphis,41,24,.631,12.0,122.6,116.8,5.8,23-10,18-14,10-5,24-16,W3,5-5,52.0,78.1%,99.8%
4,Houston,40,25,.615,13.0,112.9,108.9,4.0,22-10,18-14,12-3,24-16,W3,6-4,48.7,21.5%,94.4%
5,Golden St.,36,28,.563,16.5,113.3,111.2,2.1,18-13,18-15,2-10,20-19,W4,9-1,44.6,11.8%,65.0%
6,Minnesota,37,29,.561,16.5,112.8,109.2,3.6,18-14,19-15,7-5,26-18,W5,6-4,45.8,0.0%,78.9%
7,L.A. Clippers,35,29,.547,17.5,110.8,108.7,2.1,22-10,13-19,7-7,21-21,W3,4-6,46.8,47.9%,85.7%
8,Sacramento,33,30,.524,19.0,116.8,114.9,1.9,16-14,17-16,4-8,23-21,L1,6-4,41.7,1.7%,31.5%
9,Dallas,33,33,.500,20.5,114.8,114.5,0.3,19-15,14-18,8-5,23-23,W1,3-7,43.8,0.0%,61.3%
10,Phoenix,30,35,.462,23.0,114.5,116.5,-2.0,18-13,12-22,8-4,20-23,L1,4-6,37.7,0.0%,3.5%
11,Portland,28,37,.431,25.0,110.5,114.4,-3.9,16-15,12-22,5-9,15-29,L3,5-5,32.4,0.0%,0.0%
12,San Antonio,26,37,.413,26.0,113.7,116.1,-2.4,15-15,10-21,3-11,18-25,L3,2-8,35.9,0.0%,<1.0%
13,New Orleans,17,48,.262,36.0,110.8,119.1,-8.3,11-21,6-27,3-12,11-32,L4,4-6,24.7,0.0%,0.0%
14,Utah,15,50,.231,38.0,112.5,119.8,-7.3,8-24,7-26,2-9,7-36,L6,2-8,24.3,0.0%,0.0%

In [ ]:
# Sort by PCT in Descending Order

df_combined = df_combined.sort_values(by = 'PCT', ascending = False)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,54,10,.844,—,122.9,111.5,11.4,29-4,25-6,11-1,37-7,W14,10-0,62.9,100.0%,100.0%
0,Oklahoma City,53,12,.815,—,119.7,107.1,12.6,28-5,24-7,11-4,32-11,L1,8-2,66.1,100.0%,100.0%
1,Boston,47,18,.723,7.5,116.9,108.2,8.7,23-11,24-7,11-2,32-11,W5,8-2,59.7,98.5%,100.0%
1,Denver,42,23,.646,11.0,121.5,116.6,4.9,22-9,20-14,7-5,25-14,W1,6-4,52.8,0.0%,100.0%
2,L.A. Lakers,40,23,.635,12.0,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
2,New York,40,23,.635,13.5,116.9,112.8,4.1,21-11,19-12,10-3,28-13,L3,5-5,52.2,1.5%,100.0%
3,Memphis,41,24,.631,12.0,122.6,116.8,5.8,23-10,18-14,10-5,24-16,W3,5-5,52.0,78.1%,99.8%
4,Houston,40,25,.615,13.0,112.9,108.9,4.0,22-10,18-14,12-3,24-16,W3,6-4,48.7,21.5%,94.4%
3,Milwaukee,36,27,.571,17.5,114.6,112.5,2.1,21-11,14-16,6-6,26-18,L2,7-3,43.9,0.0%,88.5%
5,Golden St.,36,28,.563,16.5,113.3,111.2,2.1,18-13,18-15,2-10,20-19,W4,9-1,44.6,11.8%,65.0%
6,Minnesota,37,29,.561,16.5,112.8,109.2,3.6,18-14,19-15,7-5,26-18,W5,6-4,45.8,0.0%,78.9%
4,Indiana,35,28,.556,18.5,116.4,115.4,1.0,19-9,15-18,7-5,20-20,L3,5-5,46.0,0.0%,98.0%
5,Detroit,36,29,.554,18.5,114.7,113.1,1.6,17-14,19-15,4-9,24-20,W1,7-3,42.8,0.0%,88.6%
7,L.A. Clippers,35,29,.547,17.5,110.8,108.7,2.1,22-10,13-19,7-7,21-21,W3,4-6,46.8,47.9%,85.7%
8,Sacramento,33,30,.524,19.0,116.8,114.9,1.9,16-14,17-16,4-8,23-21,L1,6-4,41.7,1.7%,31.5%
9,Dallas,33,33,.500,20.5,114.8,114.5,0.3,19-15,14-18,8-5,23-23,W1,3-7,43.8,0.0%,61.3%
6,Atlanta,31,34,.477,23.5,117.3,119.7,-2.4,16-16,15-17,7-4,23-18,W3,5-5,39.0,45.7%,73.4%
10,Phoenix,30,35,.462,23.0,114.5,116.5,-2.0,18-13,12-22,8-4,20-23,L1,4-6,37.7,0.0%,3.5%
7,Orlando,30,36,.455,25.0,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
8,Miami,29,35,.453,25.0,110.0,110.5,-0.5,15-15,13-20,7-5,18-22,L4,3-7,38.5,29.8%,60.6%
11,Portland,28,37,.431,25.0,110.5,114.4,-3.9,16-15,12-22,5-9,15-29,L3,5-5,32.4,0.0%,0.0%
9,Chicago,27,38,.415,27.5,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
12,San Antonio,26,37,.413,26.0,113.7,116.1,-2.4,15-15,10-21,3-11,18-25,L3,2-8,35.9,0.0%,<1.0%
11,Philadelphia,22,42,.344,32.0,109.5,114.4,-4.9,12-21,10-21,3-10,14-26,L1,2-8,33.9,0.0%,23.6%
10,Brooklyn,22,42,.344,32.0,105.2,111.6,-6.4,10-21,12-21,3-8,12-27,W1,2-8,31.0,0.0%,2.4%
12,Toronto,22,43,.338,32.5,110.7,115.8,-5.1,15-20,7-23,4-8,14-29,W1,5-5,28.2,0.0%,<1.0%
13,New Orleans,17,48,.262,36.0,110.8,119.1,-8.3,11-21,6-27,3-12,11-32,L4,4-6,24.7,0.0%,0.0%
13,Charlotte,16,48,.250,38.0,105.3,112.8,-7.5,10-24,6-24,1-11,9-32,W2,2-8,24.1,0.0%,<1.0%
14,Utah,15,50,.231,38.0,112.5,119.8,-7.3,8-24,7-26,2-9,7-36,L6,2-8,24.3,0.0%,0.0%
14,Washington,13,50,.206,40.5,108.4,120.5,-12.1,7-25,6-24,6-6,10-27,L1,4-6,15.6,0.0%,0.0%

In [ ]:
# Reset Index

df_combined = df_combined.reset_index(drop = True)
df_combined

,Team,W,L,PCT,GB,PPG,OPPG,DIFF,HOME,ROAD,DIV,CONF,STRK,L10,W,DIV,POST
0,Cleveland,54,10,.844,—,122.9,111.5,11.4,29-4,25-6,11-1,37-7,W14,10-0,62.9,100.0%,100.0%
1,Oklahoma City,53,12,.815,—,119.7,107.1,12.6,28-5,24-7,11-4,32-11,L1,8-2,66.1,100.0%,100.0%
2,Boston,47,18,.723,7.5,116.9,108.2,8.7,23-11,24-7,11-2,32-11,W5,8-2,59.7,98.5%,100.0%
3,Denver,42,23,.646,11.0,121.5,116.6,4.9,22-9,20-14,7-5,25-14,W1,6-4,52.8,0.0%,100.0%
4,L.A. Lakers,40,23,.635,12.0,112.9,111.1,1.8,25-7,15-16,11-3,27-12,L2,8-2,46.1,38.6%,78.4%
5,New York,40,23,.635,13.5,116.9,112.8,4.1,21-11,19-12,10-3,28-13,L3,5-5,52.2,1.5%,100.0%
6,Memphis,41,24,.631,12.0,122.6,116.8,5.8,23-10,18-14,10-5,24-16,W3,5-5,52.0,78.1%,99.8%
7,Houston,40,25,.615,13.0,112.9,108.9,4.0,22-10,18-14,12-3,24-16,W3,6-4,48.7,21.5%,94.4%
8,Milwaukee,36,27,.571,17.5,114.6,112.5,2.1,21-11,14-16,6-6,26-18,L2,7-3,43.9,0.0%,88.5%
9,Golden St.,36,28,.563,16.5,113.3,111.2,2.1,18-13,18-15,2-10,20-19,W4,9-1,44.6,11.8%,65.0%
10,Minnesota,37,29,.561,16.5,112.8,109.2,3.6,18-14,19-15,7-5,26-18,W5,6-4,45.8,0.0%,78.9%
11,Indiana,35,28,.556,18.5,116.4,115.4,1.0,19-9,15-18,7-5,20-20,L3,5-5,46.0,0.0%,98.0%
12,Detroit,36,29,.554,18.5,114.7,113.1,1.6,17-14,19-15,4-9,24-20,W1,7-3,42.8,0.0%,88.6%
13,L.A. Clippers,35,29,.547,17.5,110.8,108.7,2.1,22-10,13-19,7-7,21-21,W3,4-6,46.8,47.9%,85.7%
14,Sacramento,33,30,.524,19.0,116.8,114.9,1.9,16-14,17-16,4-8,23-21,L1,6-4,41.7,1.7%,31.5%
15,Dallas,33,33,.500,20.5,114.8,114.5,0.3,19-15,14-18,8-5,23-23,W1,3-7,43.8,0.0%,61.3%
16,Atlanta,31,34,.477,23.5,117.3,119.7,-2.4,16-16,15-17,7-4,23-18,W3,5-5,39.0,45.7%,73.4%
17,Phoenix,30,35,.462,23.0,114.5,116.5,-2.0,18-13,12-22,8-4,20-23,L1,4-6,37.7,0.0%,3.5%
18,Orlando,30,36,.455,25.0,104.3,106.1,-1.8,18-16,12-20,8-3,24-20,L1,3-7,38.2,24.5%,60.9%
19,Miami,29,35,.453,25.0,110.0,110.5,-0.5,15-15,13-20,7-5,18-22,L4,3-7,38.5,29.8%,60.6%
20,Portland,28,37,.431,25.0,110.5,114.4,-3.9,16-15,12-22,5-9,15-29,L3,5-5,32.4,0.0%,0.0%
21,Chicago,27,38,.415,27.5,116.6,120.3,-3.7,12-22,15-16,4-11,22-23,W3,5-5,31.7,0.0%,3.1%
22,San Antonio,26,37,.413,26.0,113.7,116.1,-2.4,15-15,10-21,3-11,18-25,L3,2-8,35.9,0.0%,<1.0%
23,Philadelphia,22,42,.344,32.0,109.5,114.4,-4.9,12-21,10-21,3-10,14-26,L1,2-8,33.9,0.0%,23.6%
24,Brooklyn,22,42,.344,32.0,105.2,111.6,-6.4,10-21,12-21,3-8,12-27,W1,2-8,31.0,0.0%,2.4%
25,Toronto,22,43,.338,32.5,110.7,115.8,-5.1,15-20,7-23,4-8,14-29,W1,5-5,28.2,0.0%,<1.0%
26,New Orleans,17,48,.262,36.0,110.8,119.1,-8.3,11-21,6-27,3-12,11-32,L4,4-6,24.7,0.0%,0.0%
27,Charlotte,16,48,.250,38.0,105.3,112.8,-7.5,10-24,6-24,1-11,9-32,W2,2-8,24.1,0.0%,<1.0%
28,Utah,15,50,.231,38.0,112.5,119.8,-7.3,8-24,7-26,2-9,7-36,L6,2-8,24.3,0.0%,0.0%
29,Washington,13,50,.206,40.5,108.4,120.5,-12.1,7-25,6-24,6-6,10-27,L1,4-6,15.6,0.0%,0.0%